# ====> Lint (error only mode) testing
######################################################################
Using config file /home/avg/.pylintrc

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)



# ====> Unit testing
######################################################################
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK


# ====> Integration testing
######################################################################
Discover Test Args: None
* Test Suite args: None
* Running test suite 'AVG QA-12 integration tests'
  - Running Database interacation test : [  OK  ]
Ran 1 tests, 1 succeeded, 0 failed (0 expected), 0 skipped

Summary: Ran 1 tests, 1 succeeded, 0 failed (0 expected), 0 skipped


# ====> Smoke testing
######################################################################
curl to http://unoume-qa12.devops.rebrain.srwx.net status:
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx/1.14.0 (Ubuntu)
Date: Tue, 11 Aug 2020 14:42:32 GMT
Content-Type: text/html
Content-Length: 290
Connection: keep-alive



# ====> API testing
######################################################################
Discover Test Args: None
* Test Suite args: None
* Running test suite 'AVG QA-12 API tests'
  - Running Cleanup page API test        : [  OK  ]
  - Running Root page API test           : [ FAIL: did raise AttributeError: 'NoneType' object has no attribute 'get' ]
  - Running Calc page API test #1        : [  OK  ]
  - Running Calc page API test #2        : [  OK  ]
  - Running Results_secret page API test : [  OK  ]
  - Running Result/<id> page API test    : [  OK  ]

Failed tests:
========================================

-> Root page API test
----------------------------------------

did raise AttributeError: 'NoneType' object has no attribute 'get'

----------------------------------------

Ran 6 tests, 5 succeeded, 1 failed (0 expected), 0 skipped

Summary: Ran 6 tests, 5 succeeded, 1 failed (0 expected), 0 skipped


# ====> Interface testing
######################################################################
E/home/avg/.local/lib/python3.6/site-packages/requests/structures.py:58: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('31.184.254.21', 56798), raddr=('31.184.254.21', 80)>
  return (casedkey for casedkey, mappedvalue in self._store.values())
F
======================================================================
ERROR: test_calc_interface (iface_tests.TestCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/avg/qa-system/tests/iface_tests.py", line 26, in test_calc_interface
    calc_form['operation'] = operation
TypeError: 'NoneType' object does not support item assignment

======================================================================
FAIL: test_cleanup_interface (iface_tests.TestCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/avg/qa-system/tests/iface_tests.py", line 45, in test_cleanup_interface
    self.assertTrue(cleanup_form)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 2 tests in 0.031s

FAILED (failures=1, errors=1)


# ====> Load testing
######################################################################


# ====> Clean trash
######################################################################
